### ISSUE TITLE
does drf-flex-fields still recommend the direct exapnsion approach when the related resources are repeated?

### ISSUE THREAD

**Issue by simkimsia** [rsinger86/drf-flex-fields#17]
As a follow up to this comment https://github.com/rsinger86/drf-flex-fields/issues/16#issuecomment-385288690

I want to ask what if the `/users` call also include groups and the groups are repeated several times, would drf-flex-fields philosophy by default provide groups as a direct expansion approach?

**Comment by rsinger86** [comment]
It is technically possible to expand a to-many relation while listing a set of resources. (just make sure you add the expandable field to `permit_list_expands` in your viewset). However, I've moved away from this practice. If your API has multiple consumers, it is hard to satisfy all use cases. Some may want to filter the expanded groups, or not all callers should be allowed to view the expanded resources. So, you have a more stable, maintainable API if you ask the consumers to make more HTTP requests. You could give them an endpoint that allows them to filter groups by users, for instance: `/groups?users=id1,id2,id3,id4`.

**Comment by rsinger86** [comment]
closing this to keep issues list focused, but feel free to ping me if you have further questions
