### ISSUE TITLE
Deferred fields?

### ISSUE THREAD

**Issue by oliwarner** [rsinger86/drf-flex-fields#19]
Documentation talks about deferring fields but I can't get that to work. Just so we're on the same page, I have a couple of statistic fields that I want to make available but I don't want included in every query. These are annotated and pretty expensive (hence the deferral).

So here, I want to be able to annotate and display the last visit (the end of the last booking a Visitor had). The annotation itself —despite looking pretty gnarly— works.... But throwing `expand=last_visit` or `expand=last_visit&fields=last_visit` through on the querystring doesn't make the serialiser render this field.

```
class VisitorSerializer(FlexFieldsModelSerializer):
    class Meta:
        model = Visitor
        fields = ('first_name', 'second_name')
        expandable_fields = {
            'last_visit': (serializers.DateTimeField, {})
        }

class VisitorViewSet(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = Visitor.objects.all()
    serializer_class = VisitorSerializer

    permit_list_expands = ['last_visit']

    def get_queryset(self):
        queryset = super().get_queryset()

        if is_expanded(self.request, 'last_visit'):
            subq = Booking.objects.filter(visitor_bookings__visitor=OuterRef('pk')).values('timeframe')
            queryset = queryset.annotate(
                last_visit=RangeEndsWith(Subquery(subq))
            )

        return queryset
```

**Comment by rsinger86** [comment]
Hmmm, your `VisitorViewSet` class defining both `queryset` property and a `get_queryset` method threw me off  -- but it seems it's valid since the call to the super() method will get around to accessing what you've defined in the property. Just to confirm, you're sure your custom `get_queryset` method is called?

In one of my projects, I was able to implement a deferred field that serialized an annotation. So I'm kind of at a loss.

**Comment by oliwarner** [comment]
Yeah that was all working. Just found the problem though.

My serializer's expandable_fields definition is in its Meta class so wasn't being picked up. I kicked it up into the parent class and it works fine.

I'm not going to make any argument for it being in the Meta class (with the fields definition) though there might be one to make, but could you increase the indentation on your code samples to the "standard" 4-spaces? I'm just guessing but I think I assumed it was just a continuation of Meta. Perhaps put the definition before the Meta too. Just so it's double clear.
