### ISSUE TITLE
no releases in Github

### ISSUE THREAD

**Issue by kolomenkin** [rsinger86/drf-flex-fields#28]
Hi, why does this repo has no releases in Github while there are a plenty of them in PyPi?

https://pypi.org/project/drf-flex-fields/#history

I wonder what exact commit corresponds to this or that release in PyPi.

Thanks!

**Comment by rsinger86** [comment]
Hi - I've created a Github release for latest version. Thanks for the push! I'm still learning the ins and outs of github.

**Comment by kolomenkin** [comment]
Thanks a lot!

I want to notice many people are making decisions on this or that python library based on count, freshness and frequency of its releases.

So you can easily make your library looking better by adding retrospective release tags in git repo.
