### ISSUE TITLE
Add "omit" parameter to exclude unwanted serializer fields

### ISSUE THREAD

**Issue by rsinger86** [rsinger86/drf-flex-fields#6]

**Comment by stefanomunarini** [comment]
+1. There should be a built-in way to omit/exclude a specific field (e.g. the User password)

**Comment by rsinger86** [comment]
I am working on adding an "omit" parameter. Though, in the case of a password, I'd recommend not  making that available in the first place on your serialized resource representation.

**Comment by rsinger86** [comment]
Closing now that this feature is in the latest release.
