### ISSUE TITLE
FilterBackend: Include not-expanded M2M fields in prefetch-related clause

### ISSUE THREAD

**Issue by pablolmedorado** [rsinger86/drf-flex-fields#66]
Hi Robert;

First of all, thank you so much for such an amazing library! 😄

I'm testing the "FlexFieldsFilterBackend" and I think you overlooked something. Please let me know if I'm wrong.

When dealing with M2M fields, it's always desiderable to include them in prefetch_related clause, even if you're working only with pks. Otherwise, django would need to perform an extra query for every single record.

I noticed that you check if the field is expanded before including it in the prefetch_related clause. I think it should be included anyways.

https://github.com/rsinger86/drf-flex-fields/blob/bb1bd9e18a922f3605dd502332dd6073064c280a/rest_flex_fields/filter_backends.py#L49

Thanks in advance.

**Comment by rsinger86** [comment]
thanks! this should be addressed in the latest release.
