### ISSUE TITLE
`~all` or `*` should work in `fields` too

### ISSUE THREAD

**Issue by allburov** [rsinger86/drf-flex-fields#77]
Hey there! I was looking at graphql until I found you awesome library, thank you! I don't have to add another yet API :dagger: 

The question is:
We have two models with a lot of fields, e.g
```
class Order:
    field0 = ....
    field1 = ...
    ...
    field35 = ...
   restaurant=Restaurant

class Restaurant:
   field0 = ...
   field1 = ...
   ...
   field60 = ....
```

And I want to make a request that will get **All fields from Order, expand Restaurant, but only field0\field1**
How can I achieve it with drf-flex?

I tried to solve it these ways:
1. `GET /orders/?expand=restaurant` - but it gives too much fields, I really want to only two from Restaurant because we have about 100 orders in a list and all of them will contain 60 additional fields
2. `GET /orders/?fields=field0,field1,...,field35,restaurant.field0,restaurant.field1&expand=restaurant` - In this case I get that I want to, but I have to add all of fields to params, and I really don't want to do it on the frontend :) 
3. `GET /orders/?expand=restaurant` - give me too much fields too

What I really want to can be achieved with `GET /orders/?fields=~all,restaurant.field0, restaurant.field2&expand=restaurant`

But looks like `~all` works only in `expand` and not on `fields`, right?

**Comment by rsinger86** [comment]
I see your point here and agree this should should work the way you describe. I think it should go further and allow specifying all fields at nested levels, eg `fields=restaurant.*`. Hopefully I'll get to this in the next few weeks. I appreciate the useful suggestion.

**Comment by rsinger86** [comment]
@allburov Hi, finally getting back to this.

I have a branch that that should support this feature:
https://github.com/rsinger86/drf-flex-fields/tree/wildcard-for-sparse-fields

Would you mind testing to confirm it works as expected?

**Comment by allburov** [comment]
@rsinger86 Hi, thank you, I didn't expect any movements toward the issue so soon!

I'll test this out in this week!

**Comment by allburov** [comment]
Hi! I tested it and it works exactly as I expected!
`GET /?fields=*,restaurant.id,restaurant.name&expand=restaurant` gives me all fields (not expanded) from `Order` and two fields (id, name) from `Restaurant`

As you mentioned above it works for nested objects too - `GET /?fields=*,restaurant.*&expand=restaurant` expands all fields in restaurant. 
Awesome, thank you!

**Comment by rsinger86** [comment]
great, thanks for testing. i'll get this released soon.

**Comment by allburov** [comment]
I finally had a change to update the library in production and test the new feature. It works!

Thank you a lot for supporting such a great project! :)
