### ISSUE TITLE
Django 3.2 support

### ISSUE THREAD

**Issue by giovannicimolin** [rsinger86/drf-flex-fields#82]
I've run the test suite for this package on Django 3.2, and it only required minor changes to work (and still be Django 3.1 compatible).

Would you accept a PR to upgrade this package's support to Django 3.2 and fix some deprecation warnings? Let me know if so.

**Comment by rsinger86** [comment]
Thank you, this is merged. Sorry, just catching up now.

**Comment by giovannicimolin** [comment]
@rsinger86 Thanks for the review and merge :grin:
