### ISSUE TITLE
Create unique type names in FlexFieldsMixin

### ISSUE THREAD

**Issue by joeribekker** [rsinger86/drf-flex-fields#9]
All fields that are expandable will get the same serializer names. It's not directly an issue with this library but this causes issues with (for example) schema generation where names -can- be based on serializer class names.

Perhaps include the original serializer name in the generated type name.

In `views.py:50` change this:

```diff
-		return type('DynamicFieldsModelSerializer', (self.serializer_class,), {
+		return type('{}FlexFieldsSerializer'.format(self.serializer_class.__name__), (self.serializer_class,), {
			'expand': expand, 
			'include_fields': fields,
		})
```

**Comment by rsinger86** [comment]
This implementation was actually altered in the latest version. The request query params (expand and fields) now get injected via the serializer context, rather than dynamic modification of the serializer class to incorporate them. This seemed a less magical/more aligned with the DRF API.
