### ISSUE TITLE
Undocumented feature: HyperlinkedRelatedField works as expected

### ISSUE THREAD

**Issue by Semprini** [rsinger86/drf-flex-fields#91]
The FlexFieldsModelSerializer returns values for related fields by default:

`GET /api/location/region/AKL/`
```json
{
    "url": "http://127.0.0.1:8000/api/location/region/AKL/",
    "code": "AKL",
    "name": "Auckland",
    "country": "NZL"
}
```

But by specifying country as a HyperlinkedRelatedField:
```python
class RegionSerializer(FlexFieldsModelSerializer):
    country = serializers.HyperlinkedRelatedField(
        read_only=True,
        view_name='country-detail'
    )
```

We get:
```json
{
    "url": "http://127.0.0.1:8000/api/location/region/AKL/",
    "code": "AKL",
    "name": "Auckland",
    "country": "http://127.0.0.1:8000/api/location/country/NZL/"
}
```

and ?expand=country works as expected. Nice.

**Comment by rsinger86** [comment]
Interesting, it didn't occur to me this would be unexpected. 

I can update the docs to make this more clear. 

Default field definitions of fields will work as expected, but when expended, they will be overriden by the expanded version.
